stages:
  save_raw_data:
    cmd: python src/save_raw_data/save_raw_data.py
    deps:
    - src/get_parameters/get_parameters.py
    - src/save_raw_data/save_raw_data.py
    - dataset/source/dataset_source.csv
    outs:
    - dataset/raw/dataset_raw.csv

  clean_data:
    cmd: python src/clean_data/clean_data.py
    deps:
    - src/get_parameters/get_parameters.py
    - src/clean_data/clean_data.py
    - dataset/raw/dataset_raw.csv
    outs:
    - dataset/processed/dataset_no_punctuations.csv
    - dataset/processed/dataset_tokenised.csv
    - dataset/processed/dataset_no_stop_words.csv

  perform_stemming_lemmatization:
    cmd: python src/perform_stemming_lemmatization/perform_stemming_lemmatization.py
    deps:
    - src/get_parameters/get_parameters.py
    - src/perform_stemming_lemmatization/perform_stemming_lemmatization.py
    - dataset/processed/dataset_no_stop_words.csv
    outs:
    - dataset/processed/dataset_stemmed.csv
    - dataset/processed/dataset_lemmatised.csv