base:
  project_name: NLP sentiment Analysis
  dataset_name: review-datset
  target_column: Sentiment

data_source:
  store_location: dataset/source/dataset_source.csv

save_raw_data:
  dataset_raw: dataset/raw/dataset_raw.csv

feature_processing:
  dataset_no_punctuations: dataset/processed/basic_cleaning/dataset_no_punctuations.csv
  dataset_tokenised: dataset/processed/basic_cleaning/dataset_tokenised.csv
  dataset_no_stop_words: dataset/processed/basic_cleaning/dataset_no_stop_words.csv
  dataset_stemmed: dataset/processed/stemmed_lemmatised/dataset_stemmed.csv
  dataset_lemmatised: dataset/processed/stemmed_lemmatised/dataset_lemmatised.csv
  dataset_count_vectorized: dataset/processed/vectorized/dataset_count_vectorized.csv
  dataset_ngram_count_vectorized: dataset/processed/vectorized/dataset_ngram_count_vectorized.csv
  dataset_tfidf_vectorised: dataset/processed/vectorized/dataset_tfidf_vectorised.csv
  dataset_with_new_features: dataset/processed/new_features_added/dataset_with_new_features.csv

feature_analysis:
  message_length_analysis: artifacts/eda-artifacts/histograms/message_length_analysis.png
  message_length_logarithmic_analysis: artifacts/eda-artifacts/histograms/message_length_logarithmic_analysis.png
  punctuation_percent_analysis: artifacts/eda-artifacts/histograms/punctuation_percent_analysis.png
  word_cloud_bad: artifacts/eda-artifacts/word_cloud/word_cloud_bad.png
  word_cloud_neutral: artifacts/eda-artifacts/word_cloud/word_cloud_neutral.png
  word_cloud_good: artifacts/eda-artifacts/word_cloud/word_cloud_good.png
  confusion_matrix_analysis: artifacts/model-artifacts/confusion_matrix_analysis.png