base:
  project_name: NLP sentiment Analysis
  dataset_name: review-datset
  target_column: Sentiment

data_source:
  store_location: dataset/source/dataset_source.csv

save_raw_data:
  dataset_raw: dataset/raw/dataset_raw.csv

feature_processing:
  dataset_no_punctuations: dataset/processed/dataset_no_punctuations.csv
  dataset_tokenised: dataset/processed/dataset_tokenised.csv
  dataset_no_stop_words: dataset/processed/dataset_no_stop_words.csv
  dataset_clean: dataset/processed/dataset_clean.csv